/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskDialog: typeof import('./src/components/AddTaskDialog.vue')['default']
    DeleteTaskDialog: typeof import('./src/components/DeleteTaskDialog.vue')['default']
    EditTaskDialog: typeof import('./src/components/EditTaskDialog.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
